### ISSUE TITLE
`struct.unpack_from` doesn't work with `bytearray`

### ISSUE THREAD

**Issue by chubbymaggie** [ekzhu/datasketch#1]
I encounter following error while using pickle.
```
Traceback (most recent call last):
  File "srj.py", line 14, in <module>
    x1 = pickle.loads(x)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
  File "/usr/local/lib/python2.7/dist-packages/datasketch-0.1.26-py2.7.egg/datasketch/minhash.py", line 165, in __setstate__
    seed, num_perm = struct.unpack_from('qi', buffer, 0)
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray
```

From this question, I understand that its an issue in `struct.unpack_from`
http://stackoverflow.com/questions/15467009/struct-unpack-from-doesnt-work-with-bytearray

**Comment by ekzhu** [comment]
Thanks for reporting this. Have you tried running the unit tests using "nosetests"? What Python version are you using? I didn't have problem when running the following snippet from stackoverflow:

```python
struct.unpack_from('>h', bytearray('zabx'), 1)
```

**Comment by ostefano** [comment]
I can confirm the bug with python 2.7.3 (fixed in 2.7.5).
Suggested fix:
```
struct.unpack_from('>h', bytes(bytearray('zabx')), 1)
```

**Comment by ekzhu** [comment]
Thanks for the help

**Comment by ostefano** [comment]
I think tests should be updated too

```
.........E..........E.......................E
======================================================================
ERROR: test_serialize (hyperloglog_test.TestHyperLogLog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/hgfs/Lastline/python-datasketch/test/hyperloglog_test.py", line 81, in test_serialize
    self.assertEqual(h.p, struct.unpack_from('B', buf, 0)[0])
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray

======================================================================
ERROR: test_serialize (hyperloglog_test.TestHyperLogLogPlusPlus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/hgfs/Lastline/python-datasketch/test/hyperloglog_test.py", line 81, in test_serialize
    self.assertEqual(h.p, struct.unpack_from('B', buf, 0)[0])
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray

======================================================================
ERROR: test_pickle (minhash_test.TestbBitMinHash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/hgfs/Lastline/python-datasketch/test/minhash_test.py", line 217, in test_pickle
    bm2 = pickle.loads(pickle.dumps(bm))
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
  File "/mnt/hgfs/Lastline/python-datasketch/datasketch/b_bit_minhash.py", line 105, in __setstate__
    struct.unpack_from(self._serial_fmt_params, buffer, 0)
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray

----------------------------------------------------------------------
Ran 45 tests in 1.120s
```
