### ISSUE TITLE
Test pickle fails 

### ISSUE THREAD

**Issue by ostefano** [ekzhu/datasketch#3]
```
stefano@ubuntu:~/datasketch-master$ nosetests -s test/
............................................E
======================================================================
ERROR: test_pickle (minhash_test.TestbBitMinHash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefano/datasketch-master/test/minhash_test.py", line 217, in test_pickle
    bm2 = pickle.loads(pickle.dumps(bm))
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
  File "/home/stefano/datasketch-master/datasketch/b_bit_minhash.py", line 105, in __setstate__
    struct.unpack_from(self._serial_fmt_params, buffer, 0)
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray

----------------------------------------------------------------------
Ran 45 tests in 1.067s

FAILED (errors=1)
stefano@ubuntu:~/datasketch-master$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by ekzhu** [comment]
Forgot to fix b bit minhash.
