### ISSUE TITLE
NameError: global name 'RedisSetStorage' is not defined

### ISSUE THREAD

**Issue by lolgolflol** [ekzhu/datasketch#91]
I followed by example but I got this error
```
from datasketch import MinHashLSH

lsh = MinHashLSH(
   threshold=0.5, num_perm=128, storage_config={
      'type': 'redis',
      'redis': {'host': 'localhost', 'port': 6379}
  })
```

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python2.7/site-packages/datasketch/lsh.py", line 121, in __init__
    for i in range(self.b)]
  File "/usr/local/lib/python2.7/site-packages/datasketch/storage.py", line 81, in unordered_storage
    return RedisSetStorage(config, name=name)
NameError: global name 'RedisSetStorage' is not defined

**Comment by lolgolflol** [comment]
Restart computer is solved.
